<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
        }
        .container {
            margin-top: 10px;
            text-align: center;
            margin: 0;
            padding: 0;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            table-layout: auto;
        }
        .table th, .table td {
            border: 1px solid black;
            text-align: left;
            word-wrap: break-word;
            min-width: 130px;
        }
        .table th {
            background-color: #f2f2f2;
        }
        .header {
            text-align: center;
            margin: 0;
            padding: 0;
        }
        .header img {
            display: block;
            margin: 0 auto;
            width: 100px;
        }
        p {
            margin: 0;
            padding: 0;
        }
        .university {
            font-size: 20px;
            font-weight: bolder;
        }
        .report-title {
            font-size: 14px;
            font-weight: bold;
        }

        .department{
            font-size: 14px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <img src="{{ public_path('images/UCU-logo.png') }}" alt="UCU Logo">
            <p class="university">Urdaneta City University&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
            <p class="report-title">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;Reports list of Visitors&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</p>
            <p class="department">Security Management Office Report&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
        </div>
    </div>
    <div>
        <p class="text-start">Title: {{ $title }}</p>
        <p class="text-start">Date: {{ $date }}</p>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Visitor's Name</th>
                <th>Person to visit & Company</th>
                <th>Purpose</th>
                <th>Time in</th>
            </tr>
        </thead>
        <tbody>
            @foreach($visitors as $visit)
            <tr>
                <td>{{ \Carbon\Carbon::parse($visit->date)->format('F d, Y') }}</td>
                <td>{{ $visit->first_name }} {{ $visit->middle_name }}. {{ $visit->last_name }}</td>
                <td>{{ $visit->person_to_visit }}</td>
                <td>{{ $visit->purpose }}</td>
                <td>{{ \Carbon\Carbon::parse($visit->time_in)->format('g:i A') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <div class="text-start mt-4">
        <p>Generated by: {{ $user->first_name }} @if( $user->middle_name){{ $user->first_name }}.@endif {{ $user->last_name }}</p>
    </div>
</body>
</html>
