<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
        }
        .container {
            margin-top: 10px;
            text-align: center;
            margin: 0;
            padding: 0;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            table-layout: auto;
        }
        .table th, .table td {
            border: 1px solid black;
            text-align: left;
            word-wrap: break-word;
            min-width: 130px;
        }
        .table th {
            background-color: #f2f2f2;
        }
        .header {
            text-align: center;
            margin: 0;
            padding: 0;
        }
        .header img {
            display: block;
            margin: 0 auto;
            width: 100px;
        }
        p {
            margin: 0;
            padding: 0;
        }
        .university {
            font-size: 20px;
            font-weight: bolder;
        }
        .report-title {
            font-size: 14px;
            font-weight: bold;
        }

        .department{
            font-size: 14px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <img src="{{ public_path('images/UCU-logo.png') }}" alt="UCU Logo">
            <p class="university">Urdaneta City University&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
            <p class="report-title">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;Reports list of Student Violations&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</p>
            <p class="department">Security Management Office Report&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
        </div>
    </div>
    <div>
        <p class="text-start">Title: {{ $title }}</p>
        <p class="text-start">Date: {{ $date }}</p>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Student Number</th>
                <th>Name</th>
                <th>Course</th>
                <th>Violation</th>
                <th>Date</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($violations as $violate)
            <tr>
                <td>{{$violate->student_no}}</td>
                <td>{{$violate->last_name}}, {{$violate->first_name}} @if($violate->middle_initial){{$violate->middle_initial}}.@endif
                </td>
                <td>{{$violate->course}}</td>
                <td>{{$violate->violation_type}}</td>
                <td>{{$violate->date}}</td>
                <td>{{$violate->violation_count}} violation(s)</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <div class="text-start mt-4">
        <p>Generated by: {{ $user->name }}</p>
    </div>
</body>
</html>
